baseurl = "/"
#baseURL = "http://kieran.coldron.co.uk"
canonifyurls = true
paginate = 3
languageCode = "en-gb"
title = "Kieran Coldron"
copyright = "Copyright (c) 2018, all rights reserved."
theme = "hugo-dusk"

[author]
  name = "Kieran Coldron"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."

[params]
  github = "epictek"
  twitter = "epictek"
  linkedin = "kieran-coldron-3611a489"
  email = "kieran@coldron.com"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
