baseurl = "/"
#baseURL = "http://kieran.coldron.co.uk"
canonifyurls = true
paginate = 3
languageCode = "en-gb"
title = "Kieran Coldron"
copyright = "Copyright (c) 2018, all rights reserved."
theme = "hugo-dusk"

# use Chroma for syntax highlight
pygmentsStyle = "dracula" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[author]
  name = "Kieran Coldron"

SectionPagesMenu = "main"


[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."

[params]
  github = "epictek"
  twitter = "epictek"
  linkedin = "kieran-coldron"
  email = "kieran@coldron.com"

[params.colors]
  # hugo-dusk colors
  background = "#100f24" # background color for the site
  main = "#b948be"
  text = "#d0d0d0"
  code-quote-bg = "#1d1c45 !important" # background color for quotes and code blocks
  copyright = "#3b73bd" # copyright text color
